@extends('layouts.landing')
@section('content')
    <x-home-page.hero></x-home-page.hero>
    <x-home-page.about></x-home-page.about>
    <x-home-page.hose></x-home-page.hose>
    <x-home-page.benefits></x-home-page.benefits>
    <x-home-page.harmonogram></x-home-page.harmonogram>
    <x-home-page.why></x-home-page.why>
    <x-home-page.map></x-home-page.map>
    <x-home-page.financovanie></x-home-page.financovanie>
    <x-home-page.galeria></x-home-page.galeria>
    <x-home-page.c-t-a></x-home-page.c-t-a>
    <x-main-component.kontakt></x-main-component.kontakt>
@endsection